# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=31, unique=True)),
                ('sound', models.CharField(max_length=31)),
                ('weapon', models.CharField(max_length=31)),
                ('attack', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('img', models.URLField()),
                ('nat_climate', models.CharField(max_length=31)),
                ('food', models.CharField(max_length=31)),
                ('makes', models.CharField(max_length=31)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=31, unique=True)),
                ('acreage', models.IntegerField()),
                ('climate', models.CharField(max_length=31)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petorganizer.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=31, unique=True)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petorganizer.Animal')),
            ],
        ),
    ]
