# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petorganizer', '0003_zoo_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pen',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='zoo',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='zoo',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petorganizer.Pen'),
        ),
    ]
