# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petorganizer', '0004_auto_20151231_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='zoo',
            name='pen',
        )
    ]
